FROM python:3.8-slim-buster

WORKDIR /app

COPY . .
RUN pip3 install .

CMD ["panel", "serve", "--port", "5006", "survey_dashboard/", "--static-dirs en_files=./survey_dashboard/hmc_layout/static/en_files"]
