name: CI
# Main CI pipeline of the repository.
#
# Overview:
# Lint --> test doc build -\
#      \-> test code      ---> deploy docs (*) -> release (**)
#
#  (*): only on push of primary branches + release tags
# (**): only for release version tags (vX.Y.Z)

on:
  push:
    branches: [main, dev]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  publish:
    # if a version tag is pushed + tests + docs completed -> do release
    # needs: docs
    if: startswith(github.ref, 'refs/tags/v')
    permissions:
      contents: write  # for GitHub release
      id-token: write  # for PyPI release

    uses: "./.github/workflows/release.yml"
    with:
      to_github: true
      to_test_pypi: true
      to_pypi: true
